name: fitnessapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  flutter_3d_choice_chip: ^0.1.4
  page_transition: ^2.0.9
  swipeable_button_view: ^0.0.2
  share_plus: ^4.0.10
  pretty_gauge: ^1.0.1
  video_player: ^2.4.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/
