// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH7yOl_wiULVQlYMI3c5XhrKTIwR9O4Os',
    appId: '1:332076920940:web:f8b76e93486938b65d6849',
    messagingSenderId: '332076920940',
    projectId: 'fitnessapp-d30aa',
    authDomain: 'fitnessapp-d30aa.firebaseapp.com',
    storageBucket: 'fitnessapp-d30aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnnT7D8lhKIGuJ7xn8UOfwGDyFZbOnP7c',
    appId: '1:332076920940:android:9b86cee1441d44475d6849',
    messagingSenderId: '332076920940',
    projectId: 'fitnessapp-d30aa',
    storageBucket: 'fitnessapp-d30aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApQeK7F2vVJcH4euAkJyjDfpVmnDiwKV4',
    appId: '1:332076920940:ios:c8470c0cb5004f2f5d6849',
    messagingSenderId: '332076920940',
    projectId: 'fitnessapp-d30aa',
    storageBucket: 'fitnessapp-d30aa.appspot.com',
    iosClientId: '332076920940-b9hlavjeg3rbplfd859mfshmi829257o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApQeK7F2vVJcH4euAkJyjDfpVmnDiwKV4',
    appId: '1:332076920940:ios:c8470c0cb5004f2f5d6849',
    messagingSenderId: '332076920940',
    projectId: 'fitnessapp-d30aa',
    storageBucket: 'fitnessapp-d30aa.appspot.com',
    iosClientId: '332076920940-b9hlavjeg3rbplfd859mfshmi829257o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessapp',
  );
}
